system:
  ip:
  port: 8080
  env: dev
  gin_mode: release
log:
  app: go-star
  dir: logs
jwt:
  expire: 3
  secret: xxx
  issuer: xiao-wang
redis:
  addr: 43.108.109.73:6379
  password: xiaowang123!
  db: 0
db:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db: go_star
  debug: false
  source: mysql
db1:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db: go_star
  debug: false
  source: mysql